[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
NEXT_SERVERLESS = "true"
NODE_ENV = "production"
NODE_OPTIONS = "--openssl-legacy-provider"

[[redirects]]
  from = "/b"
  to = "/news"
  status = 301
  force = false
  query = {slug = ":slug"}

[functions]
  included_files = ["feed.js", "content/blog/*.md"]
